name: Sandbox
startScene: /home/jiturine/Workspace/Zafkiel/sandbox/assets/scenes/empty.zaf
assetDirectory: /home/jiturine/Workspace/Zafkiel/sandbox/assets
libraryDirectory: /home/jiturine/Workspace/Zafkiel/sandbox/library