name: Sandbox
startScene: /home/jiturine/Workspace/Zafkiel/sandbox/assets/scenes/default_scene.yaml
assetDirectory: /home/jiturine/Workspace/Zafkiel/sandbox/assets
libraryDirectory: /home/jiturine/Workspace/Zafkiel/sandbox/library